# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a208402be1538e4bef22815d00dbae9c954340b8dd78a03ebac0839aa93abb2742060f52e4906dd37015ee85c73c1951928e067f33c3a20277eaf0a87c6c631

test:
  secret_key_base: 349cef19e00257fff527973ccff3e2788ba2a48a4eea3deadd47d89a829c39944e1a07b4a73b9bc3b90bb5178cc9c44cced22f4c758c9e62aa249fb6523f3db5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
